name: Hello Earth, Hello Mars

on:
  push:
    branches:
      - main
            
jobs:
  hello_earhth: #job name
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[earth]')"
    steps:
    - run: "echo people of Earth"

  hello_mars: #job name
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[mars]')"
    steps:
    - run: "echo people of Mars "